# render instructions
services:
  - type: web
    name: libretranslate
    env: docker
    image:
      url: libretranslate/libretranslate:latest
    plan: free
    healthCheck:
      path: /
    envVars:
      - key: LT_API_KEYS
        fromEnv: LIBRETRANSLATE_API_KEY
      - key: LT_LOAD_ONLY
        value: "en,es,fr,de, zh" # English, Spanish, French, German, Chinese
      